server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;

  access_log off;
  client_max_body_size 1m;

  location = /healthz {
    default_type text/plain;
    return 200 "ok\n";
  }

  location ^~ /files/ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
  }

  location / {
    return 404;
  }
}
